---
vagrant_synced_folder_default_type: rsync

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: ilr-website.dev
vagrant_machine_name: ilr-dev-vm
vagrant_ip: 192.168.88.89

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/extras/syncing-folders/ for more info.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # build_makefile: is 'true'.
  - local_path: ../ilr-website
    destination: /var/www/ilr-website
    type: rsync
    create: true
    excluded_paths:
      - .git
      - .sass-cache
      - docs
      - db
      - migration_data
      - tmp

# Memory and CPU to use for this VM.
vagrant_memory: 4096 # Or 1/4 of the total RAM available on your computer
vagrant_cpus: 1 # For VirtualBox, see https://github.com/rdsubhas/vagrant-faster/issues/5

drupal_composer_install_dir: "/var/www/ilr-website"
drupal_composer_dependencies: []

# Set this to false if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: false

# Settings for building a Drupal site from a makefile (if 'build_makefile:'
# is 'true').
drupal_major_version: 7
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "ILR Dev Site"
drupal_install_profile: ilr
drupal_mysql_database: ilr

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  - drupalconsole
  - mailhog
  - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - varnish
  # - xdebug
  # - xhprof

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "3306"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"

php_memory_limit: "256M"
